db:
  data-source-definitions:
  - name: data-base-1
    strategy: postgres
    url: jdbc:postgresql://localhost:5441/aggregating_users1_repository
    table: user
    user: postgres
    password: postgres
    mapping:
      id: id
      username: username
      name: name
      surname: surname
  - name: data-base-2
    strategy: postgres
    url: jdbc:postgresql://localhost:5442/aggregating_users2_repository
    table: users
    user: password
    password: admin
    mapping:
      id: user_id
      username: login
      name: first_name
      surname: last_name

server:
  port: 8000
  servlet:
    context-path: /api/v1

spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 50
        show_sql: true
        format_sql: true
        hbm2ddl.auto: validate
        jdbc:
          batch_size: 50
          fetch_size: 50
    open-in-view: false
    database: postgresql
  main:
    allow-bean-definition-overriding: true


logging:
  level:
    root: info
    org.springframework.jdbc.core: trace
    com.dmdev.spring.database.pool.ConnectionPool: info
    com.dmdev.spring.database.repository.CompanyRepository: info
    com.dmdev.spring.listener: info
  file:
    name: t_aggregating_users.log
    path: /